pull_request_rules:
  - name: Label pull requests
    conditions: 
      - author=renovate[bot]
    actions:
      label:
        add: ['dependencies']
  - name: Automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
    actions:
      merge:
        method: squash
  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
